- hosts: localhost
  vars_files:
    - vars/accesos.yml
  vars:
    email_random: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=12') }}@random.local"
  tasks:
    
    - name: Crear task
      sgt_onefcc_servicenow_release:
        state: create
        authType: token
        headers: 
          Authorization: "Bearer {{ token }}"
        sn_base: https://gorest.co.in
        sn_uri: "/public/v2/users"
        data: 
          name: Prueba ansible
          gender: male
          email: "{{ email_random }}"
          status: active
      register: out_release
      tags: create

    - name: Obteniendo ID creado
      set_fact: 
        id_create: "{{ out_release.message.id }}"
        email_update: "{{ out_release.message.email }}"
      tags: create

    - name: Salida de creación de release
      debug:
        msg: "Registro {{ id_create }}, \n{{ out_release.message }}"
      tags: create

    - name: Update release
      sgt_onefcc_servicenow_release:
        state: update
        authType: token
        headers: 
          Authorization: "Bearer {{ token }}"
        sn_base: https://gorest.co.in
        sn_uri: "/public/v2/users"
        data: 
          id: "{{ id_create }}"
          name: Prueba ansible (actualizado)
          gender: male
          email: "{{ email_update }}"
          status: inactive
      register: out_release
      tags: update

    - name: Obteniendo ID actualizado
      set_fact: 
        id_update: "{{ out_release.message.id }}"
      tags: create

    - name: Salida de update de release
      debug:
        msg: "Registro {{ id_update }}, \n{{ out_release.message }}"
      tags: create
