- hosts: localhost
  gather_facts: False
  vars_files:
    - variables/common.yml
  vars:
    mensaje:
      - Despliegue de TF
      - Reinicio de TF
    task: RTSK2253318
    release: RLSE0595805

  tasks:
  
    - name: Create task to Release
      onefcc_snow_task:
        state: present
        sn_user: "{{ snow_specs.pre.user }}"
        sn_pass: "{{ snow_specs.pre.pass }}"
        sn_base: https://santandertest.service-now.com
        #release: RLSE0595100
        release: "{{ release }}"
        start_date: "2022-11-26 13:10:00"
        end_date: "2022-11-26 13:40:00"
        short_description: Realizar el {{ item }}
        description: |
          Realizar el {{ item }}

          Servidores afectados:
            pre00001.dominio.com
            pre00002.dominio.com
        state_resolve: Pre-Production
        type: Other Deployment
        group: SGT_IN_SY_ES_DEVSECOPS
        order: 100
        application: Middleware (Workday)
        technology: Middleware
        version: NA
      register: output_task
      tags: create
      with_items: "{{ mensaje }}"
    
    - name: Set Work In Progress Task
      onefcc_snow_task:
        state: in_progress
        sn_user: "{{ snow_specs.pre.user }}"
        sn_pass: "{{ snow_specs.pre.pass }}"
        sn_base: https://santandertest.service-now.com
        task: "{{ task }}"
        assigned_to: "user_sgt_pipeline_rlse"
        work_notes: "Work in Progress desde ansible {{ lookup('pipe','date +%Y-%m-%d@%H:%M:%S') }}"
      register: output_task
      tags: 
        - assigned
        - assigned_and_close

    - pause: seconds=5
      tags: 
        - close
        - assigned

    - name: Set Closed Complete Task
      onefcc_snow_task:
        state: closed
        sn_user: "{{ snow_specs.pre.user }}"
        sn_pass: "{{ snow_specs.pre.pass }}"
        sn_base: https://santandertest.service-now.com
        task: "{{ task }}"
        assigned_to: "user_sgt_pipeline_rlse"
        close_code: Successful automatic
        close_notes: Actividad ejecutada de forma automática
        work_notes: "Cerrado desde ansible {{ lookup('pipe','date +%Y-%m-%d@%H:%M:%S') }}"
      register: output_task
      tags: 
        - close
        - assigned_and_close

    - name: Get Task
      onefcc_snow_task:
        state: info
        sn_user: "{{ snow_specs.pre.user }}"
        sn_pass: "{{ snow_specs.pre.pass }}"
        sn_base: https://santandertest.service-now.com
        task: "{{ task }}"
      register: output_task
      tags: info

    - name: Printing task
      debug:
        var=output_task
      tags: 
        - info
        - create
        - assigned
        - close
        - assigned_and_close
    


        